/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.jokenpo.view;

import br.com.jokenpo.client.Client;
import br.com.jokenpo.enumeration.JokenpoEnum;

/**
 *
 * @author Lucas Laet
 */
public class JokenpoClientPane extends javax.swing.JFrame {
    
    private Client client;

    /**
     * Creates new form JokenpoClientPane
     */
    public JokenpoClientPane() {
        initComponents();
        this.client = new Client(this);
        this.client.start();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jButtonTesoura = new javax.swing.JButton();
        jButtonPedra = new javax.swing.JButton();
        jButtonPapel = new javax.swing.JButton();
        jTextFieldResult = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 48)); // NOI18N
        jLabel1.setText("JokenPÔ");

        jButtonTesoura.setText("Tesoura");
        jButtonTesoura.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonTesouraMouseClicked(evt);
            }
        });

        jButtonPedra.setText("Pedra");
        jButtonPedra.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPedraMouseClicked(evt);
            }
        });

        jButtonPapel.setText("Papel");
        jButtonPapel.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButtonPapelMouseClicked(evt);
            }
        });

        jTextFieldResult.setEditable(false);
        jTextFieldResult.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(298, 298, 298)
                        .addComponent(jLabel1))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(167, 167, 167)
                        .addComponent(jButtonPedra, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jButtonPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(55, 55, 55)
                        .addComponent(jButtonTesoura, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(63, 63, 63)
                        .addComponent(jTextFieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, 650, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(32, 32, 32)
                .addComponent(jTextFieldResult, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 44, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonPapel, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonTesoura, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButtonPedra, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(48, 48, 48))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonPedraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPedraMouseClicked
    	new Thread(() -> {
    		//hideButtons();
            this.jTextFieldResult.setText("");
    		this.writeMessage(JokenpoEnum.ROCK.getMoveName());
    	}).start();
    }//GEN-LAST:event_jButtonPedraMouseClicked

    private void jButtonPapelMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonPapelMouseClicked
    	new Thread(() -> {
    		//hideButtons();
            this.jTextFieldResult.setText("");
    		this.writeMessage(JokenpoEnum.PAPER.getMoveName());
    	}).start();
    }//GEN-LAST:event_jButtonPapelMouseClicked

    private void jButtonTesouraMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButtonTesouraMouseClicked
    	new Thread(() -> {
    		//hideButtons();
            this.jTextFieldResult.setText("");
    		this.writeMessage(JokenpoEnum.SCISSOR.getMoveName());
    	}).start();
    }//GEN-LAST:event_jButtonTesouraMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            //java.util.logging.Logger.getLogger(JokenpoClientPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            //java.util.logging.Logger.getLogger(JokenpoClientPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            //java.util.logging.Logger.getLogger(JokenpoClientPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            //java.util.logging.Logger.getLogger(JokenpoClientPane.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JokenpoClientPane().setVisible(true);
            }
        });
    }
                                                  

    private void hideButtons() {
        this.jButtonPedra.setVisible(!jButtonPedra.isVisible());
        this.jButtonPapel.setVisible(!jButtonPapel.isVisible());
        this.jButtonTesoura.setVisible(!jButtonTesoura.isVisible());
    }  
    
    private void writeMessage(String message) {
        this.jTextFieldResult.setText("");
        this.client.writeMessage(message);
    }
    
    public void showResultJokenpoPane(String resultMessage) {
        this.jTextFieldResult.setText(resultMessage);
        //this.hideButtons();
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonPapel;
    private javax.swing.JButton jButtonPedra;
    private javax.swing.JButton jButtonTesoura;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JTextField jTextFieldResult;
    // End of variables declaration//GEN-END:variables
}
